apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-data
spec:
  storageClassName: dynamic-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

