apiVersion: v1
kind: Service
metadata:
  name: litecoin-service
spec:
  selector:
    app: litecoin
  ports:
    - protocol: TCP
      port: 9333
      targetPort: 9333
  type: NodePort  # Change to ClusterIP or LoadBalancer as per your needs

